name: update-files
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4

      - name: clone repo then copy files
        run: |
          git clone --depth=1 https://github.com/UberGuidoZ/Flipper temp_source
          rsync -av --exclude='README.md' temp_source/Sub-GHz/ ./
          rm -rf temp_source

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git diff --quiet && exit 0
          git commit -m "update from UberGuidoZ/Flipper"
          
          git push origin main
